name: Library Alert

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run script
        env:
          AUTOMATION_EMAIL: ${{ secrets.AUTOMATION_EMAIL }}
          AUTOMATION_PASSWORD: ${{ secrets.AUTOMATION_PASSWORD }}
          AUTOMATION_PHONENUMBER: ${{ secrets.AUTOMATION_PHONENUMBER }}
        run: python main.py